// SPDX-License-Identifier: CC-BY-4.0

= RISC-V ACPI Platform Requirements Specification
:author: RISC-V Platform Specification Task Group
:email: tech-unixplatformspec@lists.riscv.org
:revnumber: 0.1
:sectnums:
:xrefstyle: short
:toc: macro

// table of contents
toc::[]

[preface]
== Copyright and license information

[%hardbreaks]
(C) 2021 Sunil V L <sunilvl@ventanamicro.com>

It is licensed under the Creative Commons Attribution 4.0 International
License (CC-BY 4.0). The full license text is available at
https://creativecommons.org/licenses/by/4.0/.

[preface]
== Change Log

=== Version Draft-20210812
* Initial version

== Introduction
RISC-V server class platforms need to support Advanced Configuration and Power
Interface (ACPI) as the hardware discovery and configuration mechanism. This
document describes the mandatory ACPI tables and objects for RISC-V server
platforms. All other ACPI tables not mentioned in this document can be
implemented as needed adhering to the ACPI specification.

== ACPI Namespace
In ACPI namespace, processors are required to be defined under the System Bus
*(\_SB)* name space.

== ACPI System Description Tables
The required ACPI System Description Tables, Device Objects and Methods are
listed below.

.Required ACPI System Description Tables
[cols="3,2,2", width=95%, align="center", options="header"]
|===
|ACPI Table                                    |ACPI Section|Note
|Root System Description Pointer (RSDP)        |5.2.5      |
|Extended System Description Table (XSDT)      |5.2.8      |
|Fixed ACPI Description Table (FADT)           |5.2.9      |
|Differentiated System Description Table (DSDT)|5.2.11.1   |
|Multiple APIC Description Table (MADT)        |5.2.12     |
|RISC-V Timer Description Table                |           |timebase-frequency
|Processor Properties Topology Table (PPTT)    |5.2.29     |CPU and Cache 
                                                            topology
                                                            information
|Memory-mapped Configuration space (MCFG)      |See Links to ACPI-Related 
                                                Documents (http://uefi.org/acpi)
                                                under the heading 
                                                "PCI Sig”       |Required for PCIe
                                                            support
|Debug Port Table 2 (DBG2)                     |See Links to ACPI-Related 
                                                Documents (http://uefi.org/acpi)
                                                under the heading 
                                                “Debug Port Table 2” |
|Serial Port Console Redirection (SPCR)        |See Links to ACPI-Related 
                                                Documents (http://uefi.org/acpi)
                                                under the heading 
                                                “Serial Port Console 
                                                Redirection Table” |
|System Resource Affinity Table (SRAT)         |5.2.16     |Required if the
                                                            platform supports 
                                                            NUMA
|System Locality Information Table (SLIT)      |5.2.17     |Required if the
                                                            platform supports 
                                                            NUMA
|Boot Error Record Table (BERT)                |18.3.1    | RAS APEI
|Error Injection Table (EINJ)                  |18.6.1    | RAS APEI
|Error Record Serialization Table (ERST)       |18.5      | RAS APEI
|Hardware Error Source Table (HEST)            |18.3.2    | RAS APEI
|===

== ACPI Device Objects and Methods

.Required Device Objects and Methods
[cols="1,2,3", width=95%, align="center", options="header"]
|===
|Object/Method | ACPI Section | Note
|_AEI          | 5.6.5.2     | Required for GPIO-signalled events
|_EVT          | 5.6.5.3     | Required for interrupt-signalled events
|_ADR          | 6.1.1       | Required for PCI
|_HID          | 6.1.5       |
|_UID          | 6.1.12      |
|_CRS          | 6.2.2       |
|_CCA          | 6.2.17      | Required for DMA capable devices
|_STA          | 6.3.7/7.2.4 | Device status
|===
