// UEFI Forum ECR Submission Template
//
// SPDX-License-Identifier: CC-BY-4.0
//

= UEFI Forum Engineering Change Request (ECR) 

:leveloffset: 1

= Title: 
RISCV ACLINT MTIMER ACPI Description Tables

= Status:
Draft

= Document: 
ACPI Specification 6.4.next

# License
SPDX-License-Identifier: CC-BY-4.0

= Submitter: 
Sunil V L, Ventana Micro Systems Inc.

RISC-V Platform HSC (https://lists.riscv.org/g/tech-unixplatformspec)

= Summary of the change
This ECR introduces the new RISCV Timer Description Table (RTDT) to describe the
MTIMER device of the Advanced Core Local Interruptor (ACLINT).

= Benefits of the Change
This table is required for the ACPI enabled RISCV Operating Systems to discover
the MTIMER device information.

= Impact of Change
This change will impact RISCV firmwares, different Operating Systems which
support RISCV architecture and also emulation platforms. 

= Detailed Description of the Change

Changes in [yellow-background]*yellow*

Insertions in [green-background]*green* 

Removals in [red-background line-through]*red*

== [green-background]*5.2.30 RISCV Timer Description Table (RTDT)*
[.green-background]
This section describes the format of the RISCV Timer Description Table(RTDT),
which provides OSPM with information about RISCV ACLINT MTIMER device.

[.green-background]
RISC-V platforms include an implementation of the M-level timer (MTIMER) defined
in the RISC-V Advanced Core Local Interruptor (ACLINT) specification. The
ACLINT MTIMER device is documented in the RISC-V ACLINT specification found
at https://github.com/riscv/riscv-aclint/blob/main/riscv-aclint.adoc.

[.green-background]
The ACLINT MTIMER device directly connect to the M-level timer interrupt
lines of various HARTs (or CPUs) so the RISC-V per-HART (or per-CPU) local
interrupt controller is the parent interrupt controller for the ACLINT
MTIMER device.

[.green-background]
[.text-center]
*Table 5-148 RISCV Timer Description Table (RTDT)*
[.green-background]
[cols="3,1,1,3", width=95%, align="center", options="header"]
|===
|Field             | Byte Length | Byte Offset | Description
|- Signature       | 4           | 0           | RTDT signature for the RISCV Timer Description Table
|- Length          | 4           | 4           | The length of the table, in bytes, of the entire RTDT
|- Base Frequency  | 8           | 8           | time base frequency
|- Revision        | 1           | 16          | The revision of the structure corresponding to the signature
                                                 field for this table. For the PHAT confirming to this 
                                                 revision of the specification, the revision is 1.
|- Checksum        | 1           | 17          | Entire table must sum to zero
|- Number of harts | 2           | 18          | n, Number of harts Max 511
|- Harts[n]        | 1 * n       | 20          | Hart IDs
|===
