// UEFI Forum ECR Submission Template
//
// SPDX-License-Identifier: CC-BY-4.0
//

= UEFI Forum Engineering Change Request (ECR) 

:leveloffset: 1

= Title: 
RISCV Interrupt Controller ACPI Description Tables

= Status:
Draft

= Document: 
ACPI Specification 6.4.next

# License
SPDX-License-Identifier: CC-BY-4.0

= Submitter: 
Sunil V L, Ventana Micro Systems Inc.

RISC-V Platform HSC (https://lists.riscv.org/g/tech-unixplatformspec)

= Summary of the change
This ECR introduces new Advanced Platform Interrupt Controller (APLIC), Incoming
Message Signalled Interrupt Controller (IMSIC) structures in the MADT and a new
RISCV Timer Description Table to descrbe the interrupt controllers of the RISCV
architecture.

= Benefits of the Change
It is mandatory to have these structures defined in MADT so that the RISCV
platforms can boot with ACPI. 

= Impact of Change
This change will impact RISCV firmwares, different Operating Systems which
support RISCV architecture and also emulation platforms. 

= Detailed Description of the Change

Changes in [yellow-background]*yellow*

Insertions in [green-background]*green* 

Removals in [red-background line-through]*red*


== *5.2.12 Multiple APIC Description Table (MADT)*

The ACPI interrupt model describes all interrupts for the entire system in a
uniform interrupt model implementation. Supported interrupt models include the
PC-AT-compatible dual 8259 interrupt controller, for Intel processor-based
systems, the Intel Advanced Programmable Interrupt Controller (APIC) and Intel
Streamlined Advanced Programmable Interrupt Controller (SAPIC),[red-background
line-through]#and#, for ARM processor-based systems, the Generic Interrupt
Controller (GIC) [green-background]#and for RISC-V processor-based systems, the
Advanced Platform Level Interrupt Controller (APLIC) and Incoming Message
Signaled Interrupt Controller (IMSIC)#. The choice of the interrupt model(s) to
support is up to the platform designer. The interrupt model cannot be
dynamically changed by the system firmware; OSPM will choose which model to use
and install support for that model at the time of installation. If a platform
supports multiple models, an OS will install support for only one of the models;
it will not mix models. Multi-boot capability is a feature in many modern
operating systems. This means that a system may have multiple operating systems
or multiple instances of an OS installed at any one time. Platform designers
must allow for this. This section describes the format of the Multiple APIC
Description Table (MADT), which provides OSPM with information necessary for
operation on systems with APIC, SAPIC, [red-background line-through]#or# GIC
[green-background]#or#, APLIC and IMSIC implementations.

ACPI represents all interrupts as "flat" values known as global system
interrupts. Therefore to support APICs, SAPICs [red-background
line-through]#or#, GICs, APLIC or IMSIC on an ACPI-enabled system, each used
interrupt input must be mapped to the global system interrupt value used by
ACPI. See Section 5.2.13. Global System Interrupts,” for a description of Global
System Interrupts.

Additional support is required to handle various multi-processor functions that
implementations might support (for example, identifying each processor's local
interrupt controller ID).All addresses in the MADT are processor-relative
physical addresses.

[.text-center]
Table 5-21 *Interrupt Controller Structure Types*

[cols="1,3,1,1,1", width=95%, align="center", options="header"]
|===
|Value                          | Description                                                                             | _MAT for Processor object | _MAT for an I/O APIC object | Reference
|0xF                            | GIC Interrupt Translation Service (ITS)                                                 | no                        | no                          | Section 5.2.12.18
|0x10                           | Multiprocessor Wakeup                                                                   | no                        | no                          | Section 5.2.12.19
|[green-background]#0x11#       | [green-background]#RISC-V Advanced Platform Level Interrupt Controller (APLIC)#         | [green-background]#no#    | [green-background]#no#      | [green-background]#Section 5.2.12.20#
|[green-background]#0x12#       | [green-background]#RISC-V Incoming Message Signaled Interrupt Controller Group (IMSIC)# | [green-background]#yes#   | [green-background]#no#      | [green-background]#Section 5.2.12.21#
|[yellow-background]#0x13#-0x7F | Reserved. OSPM skips structures of the reserved type.                                   | no                        | no                          |
|0x80-0xFF                      | Reserved for OEM use                                                                    | no                        | no                          |
|===

[green-background]*5.2.12.20 RISC-V  Advanced Platform Level Interrupt Controller (APLIC) Structure*

[.green-background]
In a RISC-V system, an Advanced Platform-Level Interrupt Controller (APLIC)
handles external interrupts that are signaled through wires rather than by
MSIs. The system can have multiple APLICs for converting wired interrupts
into MSIs, with each APLIC forwarding interrupts from a different subset of
devices. An individual APLIC supports a fixed number of interrupt sources,
corresponding exactly with the set of physical incoming interrupt wires at
the APLIC. APLIC can be connected to RISC-V processor and the harts in the
processor according to the platform design. Multiple APLIC structures is
possible reported in MADT for multiple RISC-V physical processor on
platform. The Privilege Modes of external interrupt is also configurable.
The properties of interrupt event source and settings of APLIC should be
configured by system firmware during POST according to the platform design.
The settings of APLIC must be reported in MADT APLIC structure by system
firmware. ACPI compliant OS can install the corresponding interrupt handler
for handling Supervisor Mode external interrupts. In the case if external
interrupt is triggered as Machine Mode external interrupt and the Machine
Mode external interrupt is not delegated to Supervisor Mode according to
interrupt domain configuration or ACPI SDEI table, OS will have to register
event handler on Machine Mode external interrupt using Supervisor Binary
Interface.

[.green-background]
[.text-center]
*Table 5-45 APLIC Structure*
[.green-background]
[cols="3,1,1,3", width=95%, align="center", options="header"]
|===
|Field                                        | Byte Length | Byte Offset | Description
|- Type                                       | 1           | 0           | 0x11 APLIC structure
|- Revision                                   | 1           | 1           | 
|- Length                                     | 2           | 2           | 
|- Total External Interrupt Sources Supported | 2           | 4           | Number of external interrupts supported in this APLIC. Minimum 1 and Maximum 1023. 
|- Number of APLIC interrupt domains          | 2           | 6           | Each APLIC can have multiple interrupt domains
|- Interrupt Domain Structure[n]              | 2 * n       | 8           | A list of interrupt domain structures in this APLIC. This structure is defined in the following section.
|===

[.green-background]
[.text-center]
*Table 5-46 Interrupt Domain Structure*
[.green-background]
[cols="3,1,1,3", width=95%, align="center", options="header"]
|===
|Field                                   | Byte Length | Byte Offset | Description
|- Mode                                  | 2           | 0           | IMSIC Mode (0-M : 1-S)
|- ID                                    | 2           | 2           | ID of the interrupt domain
|- Number of source interrupts supported | 2           | 4           | Minimum 1 and maximum 1023
|- Size                                  | 2           | 6           | Size of the interrupt domain
|- Base address                          | 8           | 8           | Offset of the interrupt domain
|- Global System Interrupt Vector Base   | 2           | 16          | Base interrupt number of Global System Interrupt of this interrupt domain. Refer to section 5.2.13 for Global System Interrupts
|- Number of target IMSIC groups         | 2           | 18          | Minimum 1 and Maximum ??
|- Target IMSIC group IDs[n]             | 2 * n       | 20          | 
|===

[green-background]*5.2.12.21 RISC-V Incoming MSI Controller (IMSIC) Structure*

[.green-background]
An Incoming MSI Controller (IMSIC) is a RISC-V hardware component that is closely
coupled with a hart, one IMSIC per hart. An IMSIC receives and records incoming
message-signaled interrupts (MSIs) for a hart, and signals to the hart when
there are pending and enabled interrupts to be serviced.

[.green-background]
The format of the IMSIC MSI Frame Structure is listed in table 5-47 below.

[.green-background]
[.text-center]
*Table 5-47 Incoming MSI Controller (IMSIC) Group Structure*
[.green-background]
[cols="3,1,1,3", width=95%, align="center", options="header"]
|===
|Field                          | Byte Length | Byte Offset | Description
|- Type                         | 1           | 0           | 0x12 IMSIC group structure
|- Revision                     | 1           | 1           | 
|- ID                           | 2           | 2           | ID of the IMSIC group
|- Mode                         | 2           | 4           | IMSIC Mode (0-M : 1-S)
|- Length                       | 2           | 6           | Size of the IMSIC frames including holes
|- Base address                 | 8           | 8           | Base address of the IMSIC frames
|- Num-ID                       | 2           | 16          | Minimum 63 maximum 2047 (One less than multiple of 64)
|- Number of harts in the group | 2           | 18          | 
|- Per-Hart-Page-Order          | 1           | 19          | Minimum 0 : Maximum 7
|- Harts[n]                     | 1 * n       | 20          | Logical HART indices in the group
|===
